import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // importing the styles

const inter = Inter({ subsets: ["latin"] });

//exports a metadata object
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //the {children here is -> the page handler component}
    <html lang="en">
      <body className={inter.className}>
        {/* hii dev this side !  */}
        <div className="p-4 border-b">

          Medium Website
        </div>
        {children}</body>
    </html>
  );
}